### ISSUE TITLE
Which language code standard do we use? 

### ISSUE THREAD

**Issue by lennertVanSever** [erasmus-without-paper/ewp-specs-api-institutions#11]
I have been looking for a while which language code standard we use. I assume that we use [ISO 639-1]( https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)? 
I hope that I don't waste anyone their time by asking this but I couldn't find it in the documentation.

**Comment by lennertVanSever** [comment]
To a further extent, I'm also wondering which Alphabet code we are using? (from the example: ru-Cyrl)

**Comment by MartaJuzepczuk** [comment]
Which element are you asking about? StringWithOptionalLang,MultilineStringWithOptionalLang and HTTPWithOptionalLang are explained here: https://github.com/erasmus-without-paper/ewp-specs-architecture/blob/stable-v1/common-types.xsd. All of them refer to xs:language type.

**Comment by janinamincer-daszkiewicz** [comment]
Lennert, is this clear now or do you expect further explanations?

**Comment by lennertVanSever** [comment]
Well the common type XML still doesn't specify which languagecode ISO is used. I assume we use ISO 639-1 since this is often used as language code.

**Comment by MartaJuzepczuk** [comment]
There was an idea to require ISO 639-1 ([see this issue](https://github.com/erasmus-without-paper/ewp-specs-architecture/issues/11)), but it was rejected (the same issue). As I remember, we don't specify anything more than [the tag documentation](http://www.rfc-editor.org/rfc/bcp/bcp47.txt).

Actually, in our implementation we also send ISO 639-1 codes (without any extensions) and when receiving, we compare the beginning of the answer with ISO 639-1. I think that for practical use it is enough.

**Comment by lennertVanSever** [comment]
Okay this is clear for me, thanks for the responses :)
