### ISSUE TITLE
Redundant XML imports in response.xsd

### ISSUE THREAD

**Issue by j-be** [erasmus-without-paper/ewp-specs-api-institutions#13]
The following XML namespaces are imported into `response.xsd`, but never actually used:

* https://github.com/erasmus-without-paper/ewp-specs-types-phonenumber/tree/stable-v1
* https://github.com/erasmus-without-paper/ewp-specs-types-academic-term/tree/stable-v1

**Comment by mkurzydlowski** [comment]
I have fixed it in https://github.com/erasmus-without-paper/ewp-specs-api-institutions/commit/715fb94c9d6ac97bbd346c58d32e651bc8c6f2f1.
